### ISSUE TITLE
the difference between few_shot_5 and few_shot_10 ? (the datasets)

### ISSUE THREAD

**Issue by MabelLIng** [few-shot-NER-benchmark/BaselineCode#3]
Excuse, the difference between few_shot_5 and few_shot_10 ? (the datasets)

**Comment by teapot123** [comment]
Hi, thanks for your interest in our paper!

The few_shot_5_x.xxx are different samples of 5-shot seeds, and few_shot_10_x.xxx are different samples of 10-shot seeds. In our main experiments (Table 2 and Table 3 in the paper), we used few_shot_5, and in training-free setting (Table 4 in the paper), we used few_shot_10.
