### ISSUE TITLE
Runing bash train_lc.sh.Got this error without modifing the code.

### ISSUE THREAD

**Issue by Godxia** [few-shot-NER-benchmark/BaselineCode#5]
Traceback (most recent call last):
  File "train_lc.py", line 539, in <module>
    t_prob = get_prob([unsup_data_], id2labels)
  File "train_lc.py", line 219, in get_prob
    loss, output, logits = model(text_1, attention_mask=attention_mask_1, labels=cls_1, dataset = dataset_chosen[j])
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by teapot123** [comment]
Hi, 
Please make sure that your code is up-to-date with our repo. I checked train_lc.py and line 219 is "val_loss += loss.mean().item()", while line 218 is 
"loss, output, logits = model(text_1, attention_mask=attention_mask_1, labels=cls_1, dataset = dataset_chosen[j], output_logits=True)", 
which is also different from your provided line 219.

**Comment by Godxia** [comment]
Thanks！ I figure out it！



---Original---
From: "Jiaxin ***@***.***&gt;
Date: Mon, May 23, 2022 01:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [few-shot-NER-benchmark/BaselineCode] Runing bash train_lc.sh.Gotthis error without modifing the code. (Issue #5)




 
Hi,
 Please make sure that your code is up-to-date with our repo. I checked train_lc.py and line 219 is "val_loss += loss.mean().item()", while line 218 is
 "loss, output, logits = model(text_1, attention_mask=attention_mask_1, labels=cls_1, dataset = dataset_chosen[j], output_logits=True)",
 which is also different from your provided line 219.
